spring:
  application:
    name: module-batch
  batch:
    jdbc:
      initialize-schema: always
        
  datasource:
    url: jdbc:mysql://localhost:33306/ready-auction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      like:
        host: localhost
        port: 16379
      auction:
        host: localhost
        port: 26379
      session:
        host: localhost
        port: 36379

  profiles:
    active: dev

server:
  port: 8081
