services:
  mysql:
    image: mysql:latest
    container_name: ready-auction-db
    restart: always # 컨테이너가 종료되면 재실행
    environment:
      MYSQL_DATABASE: ready-auction
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "33306:3306"
    volumes:
      - ./data/:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: "grafana/grafana"
    ports:
      - "13000:3000"
    restart: always
    depends_on:
      - prometheus
    privileged: true
