services:
  mysql:
    image: mysql:latest
    container_name: ready-auction-db
    environment:
      MYSQL_DATABASE: ready-auction
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/var/lib/mysql
