services:
  mysql:
    image: mysql:latest
    container_name: ready-auction-db
    restart: always # 컨테이너가 종료되면 재실행
    environment:
      MYSQL_DATABASE: ready-auction
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "33306:3306"
    volumes:
      - ./data/:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    restart: always
