services:
  mysql:
    image: mysql:latest
    container_name: ready-auction-db
    restart: always # 컨테이너가 종료되면 재실행
    environment:
      MYSQL_DATABASE: ready-auction
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "33306:3306"
    volumes:
      - ./data/:/var/lib/mysql

  redis1:
    image: redis:latest
    container_name: "likeRedis"
    volumes:
      - ./redis/redis1-data:/data
    ports:
      - "16379:6379"
    restart: always

  redis2:
    image: redis:latest
    container_name: "AuctionRedis"
    volumes:
      - ./redis/redis2-data:/data
    ports:
      - "26379:6379"
    restart: always

  redis3:
    image: redis:latest
    container_name: "SessionRedis"
    volumes:
      - ./redis/redis3-data:/data
    ports:
      - "36379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "13000:3000"
    restart: always
    depends_on:
      - prometheus
    privileged: true

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # 외부 포트
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092  # EXTERNAL만 사용
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092  # 외부 접근을 위한 주소
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT  # 외부만 PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL  # 브로커 간 통신도 EXTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
