spring:
  security:
    user:
      name: user
      password: user

  datasource:
    url: jdbc:mysql://localhost:33306/ready-auction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 16379
      password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  profiles:
    active: dev

logging:
  level:
    org.hibernate.sql: debug

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
