ready:
  auction:
    image:
      file:
        base:
          url: /Users/minjiwon/Desktop/ready-auction/Images
    recommendation:
      server:
        base:
          url: http://127.0.0.1:8085/api/v1

