spring:
  application:
    name: module-api

  datasource:
    url: jdbc:mysql://localhost:33306/ready-auction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      like:
        host: localhost
        port: 16379
      auction:
        host: localhost
        port: 26379
      session:
        host: localhost
        port: 36379

  profiles:
    active: dev

  logging:
    level:
      root: TRACE
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        waitDurationInOpenState: 30s
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 5s
        registerHealthIndicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 10
        recordFailurePredicate: com.example.moduleapi.service.httpClient.circuitBreaker.DefaultExceptionRecordFailurePredicate
    instances:
      recommendationServer:
        baseConfig: default
