spring:
  application:
    name: module-domain

  datasource:
    url: jdbc:mysql://localhost:33306/ready-auction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      like:
        host: localhost
        port: 16379
      auction:
        host: localhost
        port: 26379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    
server:
  port: 8082
